-- Defense-in-depth: enable RLS with NO policies on every table. The app
-- connects via Prisma as the postgres role (rolbypassrls=true) so it is
-- unaffected; the Supabase anon/authenticated roles (PostgREST) are denied.
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Group" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GroupMembership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Category" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Report" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReportTranslation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Entitlement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReportAccessLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DownloadToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UploadSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UploadChunk" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Symbol" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReportSymbol" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "IngestBatch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "IngestIssue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WatchlistItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReportNotification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReportAttachment" ENABLE ROW LEVEL SECURITY;
