import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Ban,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsUpDown,
  Clock,
  Copy,
  Download,
  ExternalLink,
  Eye,
  FileCheck,
  FileStack,
  FileText,
  Files,
  Filter,
  Fingerprint,
  Folder,
  FolderOpen,
  HelpCircle,
  History,
  Info,
  Key,
  Landmark,
  LayoutGrid,
  LineChart,
  List,
  Loader,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Maximize,
  Menu,
  Minimize,
  Minus,
  MoreHorizontal,
  MoreVertical,
  PanelLeft,
  Pencil,
  PieChart,
  Plus,
  Printer,
  RefreshCw,
  RotateCw,
  ScanLine,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  SlidersHorizontal,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  UserPlus,
  Users,
  Wallet,
  X,
  XCircle,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * Curated Lucide icon map (kebab-case → component), matching the bundle's
 * `<i data-lucide="…">` usage. Server-renderable (plain SVG, no hooks). The
 * thin 1.5px institutional stroke is applied via both prop and the `.lucide`
 * class (see globals.css base layer).
 */
const ICONS = {
  activity: Activity,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  archive: Archive,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  ban: Ban,
  banknote: Banknote,
  "bar-chart-3": BarChart3,
  bell: Bell,
  "book-open": BookOpen,
  briefcase: Briefcase,
  "building-2": Building2,
  calendar: Calendar,
  check: Check,
  "check-circle": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-left": ChevronsLeft,
  "chevrons-up-down": ChevronsUpDown,
  clock: Clock,
  copy: Copy,
  download: Download,
  "external-link": ExternalLink,
  eye: Eye,
  "file-check": FileCheck,
  "file-stack": FileStack,
  "file-text": FileText,
  files: Files,
  filter: Filter,
  fingerprint: Fingerprint,
  folder: Folder,
  "folder-open": FolderOpen,
  "help-circle": HelpCircle,
  history: History,
  info: Info,
  key: Key,
  landmark: Landmark,
  "layout-grid": LayoutGrid,
  "line-chart": LineChart,
  list: List,
  loader: Loader,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  maximize: Maximize,
  menu: Menu,
  minimize: Minimize,
  minus: Minus,
  "more-horizontal": MoreHorizontal,
  "more-vertical": MoreVertical,
  "panel-left": PanelLeft,
  pencil: Pencil,
  "pie-chart": PieChart,
  plus: Plus,
  printer: Printer,
  "refresh-cw": RefreshCw,
  "rotate-cw": RotateCw,
  "scan-line": ScanLine,
  search: Search,
  send: Send,
  settings: Settings,
  "share-2": Share2,
  "shield-check": ShieldCheck,
  "sliders-horizontal": SlidersHorizontal,
  "trash-2": Trash2,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  upload: Upload,
  user: User,
  "user-plus": UserPlus,
  users: Users,
  wallet: Wallet,
  x: X,
  "x-circle": XCircle,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export interface IconProps {
  name: IconName;
  size?: number;
  className?: string;
  strokeWidth?: number;
  "aria-label"?: string;
}

export function Icon({
  name,
  size = 18,
  className,
  strokeWidth = 1.5,
  ...rest
}: IconProps) {
  const Cmp = ICONS[name];
  return (
    <Cmp
      size={size}
      strokeWidth={strokeWidth}
      className={cn("lucide shrink-0", className)}
      aria-hidden={rest["aria-label"] ? undefined : true}
      {...rest}
    />
  );
}
